version: 1.0.{build}

cache:
  - packages
  
install:
    - nuget restore

build:
  project: src/BeYourMarket.sln
  publish_wap: true
  publish_nuget: true
  verbosity: minimal
  
after_test: 
    - src\packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:"".\Tests\BeYourMarket.Test\bin\Debug\BeYourMarket.Test.dll" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\BeYourMarket_coverage.xml
    - bash <(curl https://codecov.io/bash) 
